#===============================================================================
# 694_AISprites - 005_AIGen_PickerCredits.rb
# Pokedex sprite-picker integration:
#   * AI sprites appear as selectable alternates (Japeal stays available too).
#   * Selecting one shows "Generated by <MODEL_NAME>" as the creator.
# Selecting an AI sprite as the displayed sprite already works via the engine's
# existing alt-substitution path (it stores the chosen file path).
# Inert until AI files exist (the appended list is empty -> no behaviour change).
#===============================================================================
class PokemonPokedexInfo_Scene
  unless method_defined?(:aigen_orig_pbGetAvailableForms)
    alias_method :aigen_orig_pbGetAvailableForms, :pbGetAvailableForms
  end

  def pbGetAvailableForms(species = nil)
    list = aigen_orig_pbGetAvailableForms(species)
    list = [] unless list.is_a?(Array)
    return list unless AIGen.enabled?
    chosen = species != nil ? species : @species
    dexn = (getDexNumberForSpecies(chosen) rescue nil)
    return list unless dexn && dexn > NB_POKEMON
    body_id = (getBodyID(chosen) rescue nil)
    return list unless body_id
    head_id = (getHeadID(chosen, body_id) rescue nil)
    return list unless head_id
    ai_list = AIGen::Store.list(head_id, body_id)
    return list if ai_list.empty?
    ai_list.each { |p| list << p unless list.include?(p) }
    # Keep the cached bitmaps aligned with the expanded list.
    setAvailableBitmaps(list) if respond_to?(:setAvailableBitmaps)
    list
  rescue
    aigen_orig_pbGetAvailableForms(species)
  end

  unless method_defined?(:aigen_orig_showSpriteCredits)
    alias_method :aigen_orig_showSpriteCredits, :showSpriteCredits
  end

  def showSpriteCredits(filename, generated_sprite = false)
    if AIGen.enabled? && @available && @selected_index &&
       @available[@selected_index] && AIGen::Store.ai_path?(@available[@selected_index]) &&
       @creditsOverlay
      @creditsOverlay.clear
      x = Graphics.width / 2 - 75
      y = Graphics.height - 60
      label = _INTL("Generated by {1}", AIGen::MODEL_NAME)
      textpos = [[label, x, y, 0, Color.new(248, 248, 248), Color.new(104, 104, 104)]]
      pbDrawTextPositions(@creditsOverlay, textpos)
      return
    end
    aigen_orig_showSpriteCredits(filename, generated_sprite)
  end
end
