#===============================================================================
# 694_AISprites - 005_AIGen_PickerCredits.rb
# Pokedex sprite-picker integration:
#   * AI sprites appear as selectable alternates (Japeal stays available too).
#   * Selecting an AI sprite shows "Generated by <MODEL_NAME>" as the creator.
#   * Selecting a Japeal autogen fusion sprite shows "Japeal" as the creator.
# Selecting an AI sprite as the displayed sprite already works via the engine's
# existing alt-substitution path (it stores the chosen file path).
# Inert until AI files exist (the appended list is empty -> no behaviour change).
#===============================================================================
module AIGen
  # True if `path` is a Japeal / autogen FUSION sprite (lives under the Battlers
  # folder, filename is "head.body[letter]" so it contains a dot, and it is not a
  # base-species sprite, a hand-made "special" triple, an AI sprite, or a custom).
  def self.japeal_sprite?(path)
    return false unless path
    p = path.to_s
    return false if Store.ai_path?(p)
    return false if p.include?("CustomBattlers")
    bf = (defined?(Settings) && Settings.const_defined?(:BATTLERS_FOLDER)) ?
           Settings::BATTLERS_FOLDER : "Graphics/Battlers/"
    return false unless p.include?(bf)
    return false if p.include?("special/")        # hand-made triple sprites
    base = File.basename(p.sub(/\.png\z/i, ""))
    base.include?(".")                            # fusion autogen = "head.body"
  rescue
    false
  end
end

class PokemonPokedexInfo_Scene
  unless method_defined?(:aigen_orig_pbGetAvailableForms)
    alias_method :aigen_orig_pbGetAvailableForms, :pbGetAvailableForms
  end

  def pbGetAvailableForms(species = nil)
    list = aigen_orig_pbGetAvailableForms(species)
    list = [] unless list.is_a?(Array)
    return list unless AIGen.enabled?
    chosen = species != nil ? species : @species
    dexn = (getDexNumberForSpecies(chosen) rescue nil)
    return list unless dexn && dexn > NB_POKEMON
    # Triple fusion: append AI triple alts (s1.s2.s3) and return.
    if (isTripleFusion?(dexn) rescue false)
      comps = AIGen.triple_components_from_path((kuray_global_triples(dexn) rescue nil))
      if comps
        AIGen::Store.triple_list(*comps).each { |tp| list << tp unless list.include?(tp) }
        setAvailableBitmaps(list) if respond_to?(:setAvailableBitmaps)
      end
      return list
    end
    body_id = (getBodyID(chosen) rescue nil)
    return list unless body_id
    head_id = (getHeadID(chosen, body_id) rescue nil)
    return list unless head_id
    ai_list = AIGen::Store.list(head_id, body_id)
    return list if ai_list.empty?
    ai_list.each { |p| list << p unless list.include?(p) }
    # Keep the cached bitmaps aligned with the expanded list.
    setAvailableBitmaps(list) if respond_to?(:setAvailableBitmaps)
    list
  rescue
    aigen_orig_pbGetAvailableForms(species)
  end

  unless method_defined?(:aigen_orig_showSpriteCredits)
    alias_method :aigen_orig_showSpriteCredits, :showSpriteCredits
  end

  def showSpriteCredits(filename, generated_sprite = false)
    if AIGen.enabled? && @available && @selected_index &&
       @available[@selected_index] && @creditsOverlay
      sel = @available[@selected_index]
      label = nil
      if AIGen::Store.ai_path?(sel)
        label = _INTL("Generated by {1}", AIGen::MODEL_NAME)
      elsif AIGen.japeal_sprite?(sel)
        label = _INTL("Japeal")
      end
      if label
        @creditsOverlay.clear
        x = Graphics.width / 2
        y = Graphics.height - 60
        textpos = [[label, x, y, 2, Color.new(248, 248, 248), Color.new(104, 104, 104)]]
        pbDrawTextPositions(@creditsOverlay, textpos)
        return
      end
    end
    aigen_orig_showSpriteCredits(filename, generated_sprite)
  end
end
