#===============================================================================
# 694_AISprites - 008_AIGen_FusionScreen.rb
# Fusion preview (FusionPreviewScreen < DoublePreviewScreen):
#
#  * AUTO-FILL: when the preview opens, any direction that has only a Japeal
#    autogen sprite (no human custom, no AI yet) is auto-generated by our model
#    and shown in place. The Japeal sprite stays available as an alternate in the
#    Pokedex sprite picker. A direction that has a human custom sprite is left
#    exactly as-is.
#
#  * Press Input::ACTION on the preview to open the AI menu (Generate /
#    Regenerate / Delete both directions).
#
#  * INLINE REGENERATE: when the Fusion Preview option is ON and BOTH shown
#    sprites are ours (neither direction had a human custom), an on-screen hint
#    invites a one-press Regenerate that deletes the previous AI sprites for this
#    pair and makes new ones. Human custom sprites are NEVER deleted.
#
# Everything is wrapped so it can never break fusing.
#===============================================================================
class DoublePreviewScreen
  unless method_defined?(:aigen_orig_draw_window)
    alias_method :aigen_orig_draw_window, :draw_window
    def draw_window(dexNumber, level, x, y, shiny, shinyV, shinyR, shinyG, shinyB, shinyKRS, shinyOmega = {})
      win = aigen_orig_draw_window(dexNumber, level, x, y, shiny, shinyV, shinyR, shinyG, shinyB, shinyKRS, shinyOmega)
      begin
        @aigen_draw_args ||= {}
        @aigen_draw_args[x] = [dexNumber, level, x, y]
      rescue
      end
      win
    end
  end

  unless method_defined?(:aigen_orig_startSelection)
    alias_method :aigen_orig_startSelection, :startSelection
    def startSelection
      (aigen_preview_autofill rescue nil)
      aigen_orig_startSelection
    end
  end

  unless method_defined?(:aigen_orig_updateSelection)
    alias_method :aigen_orig_updateSelection, :updateSelection
    def updateSelection
      aigen_orig_updateSelection
      if AIGen.enabled? && Input.trigger?(Input::ACTION)
        aigen_fusion_menu
      end
    end
  end

  def aigen_fusion_pair
    if @poke1 && @poke2 && @poke1.respond_to?(:species_data) && @poke2.respond_to?(:species_data)
      return [@poke1.species_data.id_number, @poke2.species_data.id_number]
    end
    nil
  end

  def aigen_preview_option_on?
    defined?($PokemonSystem) && $PokemonSystem &&
      $PokemonSystem.respond_to?(:kurayfusepreview) && $PokemonSystem.kurayfusepreview == 1
  end

  def aigen_dir_needs_ai?(h, bd)
    return false if AIGen::Store.human_custom?(h, bd)
    !AIGen::Store.main_sprite_path(h, bd)
  end

  def aigen_dir_is_ai?(h, bd)
    return false if AIGen::Store.human_custom?(h, bd)
    !!AIGen::Store.main_sprite_path(h, bd)
  end

  def aigen_preview_autofill
    return if @aigen_autofilled
    @aigen_autofilled = true
    return unless AIGen.enabled?
    ids = aigen_fusion_pair
    return unless ids
    a, b = ids
    need = [[a, b], [b, a]].select { |h, bd| aigen_dir_needs_ai?(h, bd) }
    # Only spend time here on a fork where the model is actually installed, so a
    # fusion preview never freezes where AI sprites were never set up.
    if !need.empty? && AIGen::Launcher.launchable?
      busy = (aigen_show_busy(_INTL("Generating fusion sprite with {1}...", AIGen::MODEL_NAME)) rescue nil)
      if AIGen::Launcher.ensure_running(30)
        made = false
        need.each { |h, bd| made = true if AIGen.generate(h, bd) }
        (aigen_hide_busy(busy) rescue nil)
        aigen_redraw_previews if made
      else
        (aigen_hide_busy(busy) rescue nil)
      end
    end
    aigen_update_regen_hint
  rescue Exception => e
    AIGen.log("preview autofill error: #{e.message}")
  end

  def aigen_update_regen_hint
    ids = aigen_fusion_pair
    show = false
    if ids && AIGen.enabled? && aigen_preview_option_on?
      a, b = ids
      show = aigen_dir_is_ai?(a, b) && aigen_dir_is_ai?(b, a)
    end
    if show
      @aigen_regen_hint ||= BitmapSprite.new(Graphics.width, Graphics.height, @viewport)
      @aigen_regen_hint.z = 100002
      @aigen_regen_hint.bitmap.clear
      pbDrawTextPositions(@aigen_regen_hint.bitmap,
        [[_INTL("Press ACTION: Regenerate AI sprites"), 8, 2, 0,
          Color.new(248, 248, 248), Color.new(104, 104, 104)]])
    elsif @aigen_regen_hint
      @aigen_regen_hint.bitmap.clear
    end
  rescue
  end

  def aigen_show_busy(text)
    spr = BitmapSprite.new(Graphics.width, Graphics.height, @viewport)
    spr.z = 100003
    pbDrawTextPositions(spr.bitmap,
      [[text, Graphics.width / 2, Graphics.height / 2 - 8, 2,
        Color.new(248, 248, 248), Color.new(104, 104, 104)]])
    (Graphics.update rescue nil)
    spr
  end

  def aigen_hide_busy(spr)
    return unless spr
    spr.bitmap.dispose if spr.bitmap && !spr.bitmap.disposed?
    spr.dispose unless spr.disposed?
  rescue
  end

  def aigen_fusion_menu
    ids = aigen_fusion_pair
    return unless ids
    a, b = ids
    both_ai = aigen_dir_is_ai?(a, b) && aigen_dir_is_ai?(b, a)
    has_ai  = !!(AIGen::Store.main_sprite_path(a, b) || AIGen::Store.main_sprite_path(b, a))

    cmds = []; acts = []
    if both_ai
      cmds << _INTL("Regenerate AI sprites"); acts << :regen_fresh
    end
    cmds << _INTL("Generate AI sprites (both fusions)"); acts << :gen
    if has_ai && !both_ai
      cmds << _INTL("Regenerate AI sprites (both)"); acts << :regen
    end
    if has_ai
      cmds << _INTL("Delete AI sprites (both)"); acts << :del
    end
    cmds << _INTL("Cancel"); acts << :cancel

    choice = pbMessage(_INTL("AI fusion sprites ({1}):", AIGen::MODEL_NAME), cmds, cmds.length)
    case acts[choice]
    when :gen         then aigen_fusion_run(a, b, false)
    when :regen       then aigen_fusion_run(a, b, true)
    when :regen_fresh then aigen_fusion_regenerate_fresh(a, b)
    when :del         then aigen_fusion_delete(a, b)
    end
  rescue Exception => e
    AIGen.log("fusion menu error: #{e.message}")
    (pbMessage(_INTL("AI sprite generation hit an error and was skipped.")) rescue nil)
  end

  def aigen_fusion_run(a, b, regen)
    unless AIGen::Launcher.ensure_running(30)
      pbMessage(_INTL("The AI sprite model isn't running.\nStart the sidecar and try again."))
      return
    end
    busy = (aigen_show_busy(_INTL("Working with {1}...", AIGen::MODEL_NAME)) rescue nil)
    made = 0
    [[a, b], [b, a]].each do |h, bd|
      path = regen ? AIGen.regenerate(h, bd, "") : AIGen.generate(h, bd)
      made += 1 if path
    end
    (aigen_hide_busy(busy) rescue nil)
    aigen_redraw_previews
    aigen_update_regen_hint
    if made >= 2
      pbMessage(regen ? _INTL("Regenerated both fusion sprites!") : _INTL("AI sprites generated for both fusions!"))
    elsif made == 1
      pbMessage(_INTL("Only one fusion direction worked.\nPress ACTION again to retry the other."))
    else
      pbMessage(_INTL("The AI sprite model didn't return any images.\nPlease try again."))
    end
  rescue Exception => e
    AIGen.log("fusion run error: #{e.message}")
    (pbMessage(_INTL("AI sprite generation hit an error and was skipped.")) rescue nil)
  end

  def aigen_fusion_regenerate_fresh(a, b)
    unless AIGen::Launcher.ensure_running(30)
      pbMessage(_INTL("The AI sprite model isn't running.\nStart the sidecar and try again."))
      return
    end
    busy = (aigen_show_busy(_INTL("Regenerating with {1}...", AIGen::MODEL_NAME)) rescue nil)
    [[a, b], [b, a]].each do |h, bd|
      AIGen::Store.list(h, bd).each { |p| AIGen::Store.delete(p) }
    end
    if defined?($PokemonGlobal) && $PokemonGlobal &&
       $PokemonGlobal.respond_to?(:alt_sprite_substitutions) && $PokemonGlobal.alt_sprite_substitutions
      $PokemonGlobal.alt_sprite_substitutions.delete_if { |_k, v| AIGen::Store.ai_path?(v) }
    end
    made = 0
    [[a, b], [b, a]].each { |h, bd| made += 1 if AIGen.generate(h, bd) }
    (aigen_hide_busy(busy) rescue nil)
    aigen_redraw_previews
    aigen_update_regen_hint
    pbMessage(made >= 1 ? _INTL("Regenerated the fusion sprites!") :
                          _INTL("The AI sprite model didn't return any images.\nPlease try again."))
  rescue Exception => e
    AIGen.log("fusion regen-fresh error: #{e.message}")
    (pbMessage(_INTL("AI sprite regeneration hit an error and was skipped.")) rescue nil)
  end

  def aigen_fusion_delete(a, b)
    n = 0
    [[a, b], [b, a]].each do |h, bd|
      AIGen::Store.list(h, bd).each { |p| n += 1 if AIGen::Store.delete(p) }
    end
    if defined?($PokemonGlobal) && $PokemonGlobal &&
       $PokemonGlobal.respond_to?(:alt_sprite_substitutions) && $PokemonGlobal.alt_sprite_substitutions
      $PokemonGlobal.alt_sprite_substitutions.delete_if { |_k, v| AIGen::Store.ai_path?(v) }
    end
    aigen_redraw_previews
    aigen_update_regen_hint
    pbMessage(n > 0 ? _INTL("Deleted {1} AI sprite(s).", n) : _INTL("There were no AI sprites to delete."))
  rescue Exception => e
    AIGen.log("fusion delete error: #{e.message}")
    (pbMessage(_INTL("Couldn't delete the AI sprites.")) rescue nil)
  end

  def aigen_redraw_previews
    return unless @aigen_draw_args
    [[20, :@picture1, "picture1"], [270, :@picture2, "picture2"]].each do |x, ivar, key|
      args = @aigen_draw_args[x]
      next unless args
      old = instance_variable_get(ivar)
      neww = aigen_orig_draw_window(args[0], args[1], args[2], args[3],
                                    false, false, 0, 1, 2, [0, 0, 0, 0, 0, 0, 0, 0, 0], {})
      instance_variable_set(ivar, neww)
      @sprites[key] = neww if @sprites
      (old.dispose if old && old.respond_to?(:dispose)) rescue nil
    end
    (pbUpdateSpriteHash(@sprites) rescue nil)
  end
end
